/*
 * Copyright 1999-2022 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.csp.sentinel.adapter.jdbc;

import com.alibaba.csp.sentinel.adapter.jdbc.delegate.ConnectionDelegate;

import java.sql.*;
import java.util.function.Function;

/**
 * @author icodening
 * @date 2022.02.08
 */
public class SentinelJDBCConnection extends ConnectionDelegate {

    private Function<String, String> sqlMapper;

    public SentinelJDBCConnection(Connection delegate) {
        super(delegate);
    }

    public SentinelJDBCConnection(Connection delegate, Function<String, String> sqlMapper) {
        super(delegate);
        setSQLMapper(sqlMapper);
    }

    public void setSQLMapper(Function<String, String> sqlMapper) {
        this.sqlMapper = sqlMapper;
    }

    @Override
    public Statement createStatement() throws SQLException {
        return new SentinelJDBCStatement(super.createStatement(), sqlMapper);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new SentinelJDBCStatement(super.createStatement(resultSetType, resultSetConcurrency), sqlMapper);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new SentinelJDBCStatement(super.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), sqlMapper);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        SentinelJDBCPreparedStatement sentinelJDBCPreparedStatement =
                new SentinelJDBCPreparedStatement(super.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sqlMapper);
        sentinelJDBCPreparedStatement.setSQL(sql);
        return sentinelJDBCPreparedStatement;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        SentinelJDBCPreparedStatement sentinelJDBCPreparedStatement =
                new SentinelJDBCPreparedStatement(super.prepareStatement(sql, autoGeneratedKeys), sqlMapper);
        sentinelJDBCPreparedStatement.setSQL(sql);
        return sentinelJDBCPreparedStatement;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        SentinelJDBCPreparedStatement sentinelJDBCPreparedStatement =
                new SentinelJDBCPreparedStatement(super.prepareStatement(sql, columnIndexes), sqlMapper);
        sentinelJDBCPreparedStatement.setSQL(sql);
        return sentinelJDBCPreparedStatement;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        SentinelJDBCPreparedStatement sentinelJDBCPreparedStatement =
                new SentinelJDBCPreparedStatement(super.prepareStatement(sql, columnNames), sqlMapper);
        sentinelJDBCPreparedStatement.setSQL(sql);
        return sentinelJDBCPreparedStatement;
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        SentinelJDBCPreparedStatement sentinelJDBCPreparedStatement =
                new SentinelJDBCPreparedStatement(super.prepareStatement(sql), sqlMapper);
        sentinelJDBCPreparedStatement.setSQL(sql);
        return sentinelJDBCPreparedStatement;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        SentinelJDBCPreparedStatement sentinelJDBCPreparedStatement =
                new SentinelJDBCPreparedStatement(super.prepareStatement(sql, resultSetType, resultSetConcurrency), sqlMapper);
        sentinelJDBCPreparedStatement.setSQL(sql);
        return sentinelJDBCPreparedStatement;
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        SentinelCallableStatement sentinelCallableStatement = new SentinelCallableStatement(super.prepareCall(sql), sqlMapper);
        sentinelCallableStatement.setSQL(sql);
        return sentinelCallableStatement;
    }
}
