// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ca.proto

package com.alibaba.csp.sentinel.datasource.xds.client.grpc;

/**
 * <pre>
 * Certificate request message. The authentication should be based on:
 * 1. Bearer tokens carried in the side channel;
 * 2. Client-side certificate via Mutual TLS handshake.
 * Note: the service implementation is REQUIRED to verify the authenticated caller is authorize to
 * all SANs in the CSR. The server side may overwrite any requested certificate field based on its
 * policies.
 * </pre>
 * <p>
 * Protobuf type {@code istio.v1.auth.IstioCertificateRequest}
 */
public final class IstioCertificateRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:istio.v1.auth.IstioCertificateRequest)
    IstioCertificateRequestOrBuilder {

    public static final int CSR_FIELD_NUMBER = 1;
    public static final int VALIDITY_DURATION_FIELD_NUMBER = 3;
    public static final int METADATA_FIELD_NUMBER = 4;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:istio.v1.auth.IstioCertificateRequest)
    private static final IstioCertificateRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<IstioCertificateRequest> PARSER
        = new com.google.protobuf.AbstractParser<IstioCertificateRequest>() {
        @Override
        public IstioCertificateRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new IstioCertificateRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new IstioCertificateRequest();
    }

    private volatile Object csr_;
    private long validityDuration_;
    private com.google.protobuf.Struct metadata_;
    private byte memoizedIsInitialized = -1;

    // Use IstioCertificateRequest.newBuilder() to construct.
    private IstioCertificateRequest(
        com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private IstioCertificateRequest() {
        csr_ = "";
    }

    private IstioCertificateRequest(com.google.protobuf.CodedInputStream input,
                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
            .newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        csr_ = s;
                        break;
                    }
                    case 24: {

                        validityDuration_ = input.readInt64();
                        break;
                    }
                    case 34: {
                        com.google.protobuf.Struct.Builder subBuilder = null;
                        if (metadata_ != null) {
                            subBuilder = metadata_.toBuilder();
                        }
                        metadata_ = input.readMessage(com.google.protobuf.Struct.parser(),
                            extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(metadata_);
                            metadata_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry,
                            tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return Ca.internal_static_istio_v1_auth_IstioCertificateRequest_descriptor;
    }

    public static IstioCertificateRequest parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IstioCertificateRequest parseFrom(java.nio.ByteBuffer data,
                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IstioCertificateRequest parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IstioCertificateRequest parseFrom(com.google.protobuf.ByteString data,
                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IstioCertificateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IstioCertificateRequest parseFrom(byte[] data,
                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IstioCertificateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static IstioCertificateRequest parseFrom(java.io.InputStream input,
                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static IstioCertificateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static IstioCertificateRequest parseDelimitedFrom(java.io.InputStream input,
                                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static IstioCertificateRequest parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static IstioCertificateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(IstioCertificateRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static IstioCertificateRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<IstioCertificateRequest> parser() {
        return PARSER;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(UnusedPrivateParameter unused) {
        return new IstioCertificateRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
        return Ca.internal_static_istio_v1_auth_IstioCertificateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(IstioCertificateRequest.class,
                Builder.class);
    }

    /**
     * <pre>
     * PEM-encoded certificate request.
     * The public key in the CSR is used to generate the certificate,
     * and other fields in the generated certificate may be overwritten by the CA.
     * </pre>
     *
     * <code>string csr = 1;</code>
     *
     * @return The csr.
     */
    @Override
    public String getCsr() {
        Object ref = csr_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            csr_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * PEM-encoded certificate request.
     * The public key in the CSR is used to generate the certificate,
     * and other fields in the generated certificate may be overwritten by the CA.
     * </pre>
     *
     * <code>string csr = 1;</code>
     *
     * @return The bytes for csr.
     */
    @Override
    public com.google.protobuf.ByteString getCsrBytes() {
        Object ref = csr_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                .copyFromUtf8((String) ref);
            csr_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * Optional: requested certificate validity period, in seconds.
     * </pre>
     *
     * <code>int64 validity_duration = 3;</code>
     *
     * @return The validityDuration.
     */
    @Override
    public long getValidityDuration() {
        return validityDuration_;
    }

    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     *
     * @return Whether the metadata field is set.
     */
    @Override
    public boolean hasMetadata() {
        return metadata_ != null;
    }

    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     *
     * @return The metadata.
     */
    @Override
    public com.google.protobuf.Struct getMetadata() {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance()
            : metadata_;
    }

    /**
     * <pre>
     * $hide_from_docs
     * Optional: Opaque metadata provided by the XDS node to Istio.
     * Supported metadata: WorkloadName, WorkloadIP, ClusterID
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 4;</code>
     */
    @Override
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
        return getMetadata();
    }

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (!getCsrBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, csr_);
        }
        if (validityDuration_ != 0L) {
            output.writeInt64(3, validityDuration_);
        }
        if (metadata_ != null) {
            output.writeMessage(4, getMetadata());
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (!getCsrBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, csr_);
        }
        if (validityDuration_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(3,
                validityDuration_);
        }
        if (metadata_ != null) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(4,
                getMetadata());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof IstioCertificateRequest)) {
            return super.equals(obj);
        }
        IstioCertificateRequest other = (IstioCertificateRequest) obj;

        if (!getCsr().equals(other.getCsr())) {
            return false;
        }
        if (getValidityDuration() != other.getValidityDuration()) {
            return false;
        }
        if (hasMetadata() != other.hasMetadata()) {
            return false;
        }
        if (hasMetadata()) {
            if (!getMetadata().equals(other.getMetadata())) {
                return false;
            }
        }
        if (!unknownFields.equals(other.unknownFields)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CSR_FIELD_NUMBER;
        hash = (53 * hash) + getCsr().hashCode();
        hash = (37 * hash) + VALIDITY_DURATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getValidityDuration());
        if (hasMetadata()) {
            hash = (37 * hash) + METADATA_FIELD_NUMBER;
            hash = (53 * hash) + getMetadata().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<IstioCertificateRequest> getParserForType() {
        return PARSER;
    }

    @Override
    public IstioCertificateRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * Certificate request message. The authentication should be based on:
     * 1. Bearer tokens carried in the side channel;
     * 2. Client-side certificate via Mutual TLS handshake.
     * Note: the service implementation is REQUIRED to verify the authenticated caller is authorize to
     * all SANs in the CSR. The server side may overwrite any requested certificate field based on its
     * policies.
     * </pre>
     * <p>
     * Protobuf type {@code istio.v1.auth.IstioCertificateRequest}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:istio.v1.auth.IstioCertificateRequest)
        IstioCertificateRequestOrBuilder {

        private Object csr_ = "";
        private long validityDuration_;
        private com.google.protobuf.Struct metadata_;
        private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Struct,
            com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>
            metadataBuilder_;

        // Construct using istio.v1.auth.IstioCertificateRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return Ca.internal_static_istio_v1_auth_IstioCertificateRequest_descriptor;
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return Ca.internal_static_istio_v1_auth_IstioCertificateRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(IstioCertificateRequest.class,
                    Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            csr_ = "";

            validityDuration_ = 0L;

            if (metadataBuilder_ == null) {
                metadata_ = null;
            } else {
                metadata_ = null;
                metadataBuilder_ = null;
            }
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return Ca.internal_static_istio_v1_auth_IstioCertificateRequest_descriptor;
        }

        @Override
        public IstioCertificateRequest getDefaultInstanceForType() {
            return IstioCertificateRequest.getDefaultInstance();
        }

        @Override
        public IstioCertificateRequest build() {
            IstioCertificateRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IstioCertificateRequest buildPartial() {
            IstioCertificateRequest result = new IstioCertificateRequest(this);
            result.csr_ = csr_;
            result.validityDuration_ = validityDuration_;
            if (metadataBuilder_ == null) {
                result.metadata_ = metadata_;
            } else {
                result.metadata_ = metadataBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field, int index,
            Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof IstioCertificateRequest) {
                return mergeFrom((IstioCertificateRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(IstioCertificateRequest other) {
            if (other == IstioCertificateRequest.getDefaultInstance()) {
                return this;
            }
            if (!other.getCsr().isEmpty()) {
                csr_ = other.csr_;
                onChanged();
            }
            if (other.getValidityDuration() != 0L) {
                setValidityDuration(other.getValidityDuration());
            }
            if (other.hasMetadata()) {
                mergeMetadata(other.getMetadata());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            IstioCertificateRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (IstioCertificateRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <pre>
         * PEM-encoded certificate request.
         * The public key in the CSR is used to generate the certificate,
         * and other fields in the generated certificate may be overwritten by the CA.
         * </pre>
         *
         * <code>string csr = 1;</code>
         *
         * @return The csr.
         */
        public String getCsr() {
            Object ref = csr_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                csr_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * PEM-encoded certificate request.
         * The public key in the CSR is used to generate the certificate,
         * and other fields in the generated certificate may be overwritten by the CA.
         * </pre>
         *
         * <code>string csr = 1;</code>
         *
         * @param value The csr to set.
         * @return This builder for chaining.
         */
        public Builder setCsr(String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            csr_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * PEM-encoded certificate request.
         * The public key in the CSR is used to generate the certificate,
         * and other fields in the generated certificate may be overwritten by the CA.
         * </pre>
         *
         * <code>string csr = 1;</code>
         *
         * @return The bytes for csr.
         */
        public com.google.protobuf.ByteString getCsrBytes() {
            Object ref = csr_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                    .copyFromUtf8((String) ref);
                csr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * PEM-encoded certificate request.
         * The public key in the CSR is used to generate the certificate,
         * and other fields in the generated certificate may be overwritten by the CA.
         * </pre>
         *
         * <code>string csr = 1;</code>
         *
         * @param value The bytes for csr to set.
         * @return This builder for chaining.
         */
        public Builder setCsrBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            csr_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * PEM-encoded certificate request.
         * The public key in the CSR is used to generate the certificate,
         * and other fields in the generated certificate may be overwritten by the CA.
         * </pre>
         *
         * <code>string csr = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCsr() {

            csr_ = getDefaultInstance().getCsr();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Optional: requested certificate validity period, in seconds.
         * </pre>
         *
         * <code>int64 validity_duration = 3;</code>
         *
         * @return The validityDuration.
         */
        @Override
        public long getValidityDuration() {
            return validityDuration_;
        }

        /**
         * <pre>
         * Optional: requested certificate validity period, in seconds.
         * </pre>
         *
         * <code>int64 validity_duration = 3;</code>
         *
         * @param value The validityDuration to set.
         * @return This builder for chaining.
         */
        public Builder setValidityDuration(long value) {

            validityDuration_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Optional: requested certificate validity period, in seconds.
         * </pre>
         *
         * <code>int64 validity_duration = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearValidityDuration() {

            validityDuration_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         *
         * @return Whether the metadata field is set.
         */
        public boolean hasMetadata() {
            return metadataBuilder_ != null || metadata_ != null;
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         *
         * @return The metadata.
         */
        public com.google.protobuf.Struct getMetadata() {
            if (metadataBuilder_ == null) {
                return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance()
                    : metadata_;
            } else {
                return metadataBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         */
        public Builder setMetadata(com.google.protobuf.Struct value) {
            if (metadataBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                metadata_ = value;
                onChanged();
            } else {
                metadataBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         */
        public Builder setMetadata(com.google.protobuf.Struct.Builder builderForValue) {
            if (metadataBuilder_ == null) {
                metadata_ = builderForValue.build();
                onChanged();
            } else {
                metadataBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         */
        public Builder mergeMetadata(com.google.protobuf.Struct value) {
            if (metadataBuilder_ == null) {
                if (metadata_ != null) {
                    metadata_ = com.google.protobuf.Struct.newBuilder(metadata_)
                        .mergeFrom(value).buildPartial();
                } else {
                    metadata_ = value;
                }
                onChanged();
            } else {
                metadataBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         */
        public Builder clearMetadata() {
            if (metadataBuilder_ == null) {
                metadata_ = null;
                onChanged();
            } else {
                metadata_ = null;
                metadataBuilder_ = null;
            }

            return this;
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         */
        public com.google.protobuf.Struct.Builder getMetadataBuilder() {

            onChanged();
            return getMetadataFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         */
        public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
            if (metadataBuilder_ != null) {
                return metadataBuilder_.getMessageOrBuilder();
            } else {
                return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance()
                    : metadata_;
            }
        }

        /**
         * <pre>
         * $hide_from_docs
         * Optional: Opaque metadata provided by the XDS node to Istio.
         * Supported metadata: WorkloadName, WorkloadIP, ClusterID
         * </pre>
         *
         * <code>.google.protobuf.Struct metadata = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Struct,
            com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> getMetadataFieldBuilder() {
            if (metadataBuilder_ == null) {
                metadataBuilder_
                    = new com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Struct,
                    com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                    getMetadata(), getParentForChildren(), isClean());
                metadata_ = null;
            }
            return metadataBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:istio.v1.auth.IstioCertificateRequest)

    }

}
