// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ca.proto

package com.alibaba.csp.sentinel.datasource.xds.client.grpc;

/**
 * <pre>
 * Certificate response message.
 * </pre>
 * <p>
 * Protobuf type {@code istio.v1.auth.IstioCertificateResponse}
 */
public final class IstioCertificateResponse extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:istio.v1.auth.IstioCertificateResponse)
    IstioCertificateResponseOrBuilder {

    public static final int CERT_CHAIN_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:istio.v1.auth.IstioCertificateResponse)
    private static final IstioCertificateResponse DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<IstioCertificateResponse> PARSER
        = new com.google.protobuf.AbstractParser<IstioCertificateResponse>() {
        @Override
        public IstioCertificateResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new IstioCertificateResponse(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new IstioCertificateResponse();
    }

    private com.google.protobuf.LazyStringList certChain_;
    private byte memoizedIsInitialized = -1;

    // Use IstioCertificateResponse.newBuilder() to construct.
    private IstioCertificateResponse(
        com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private IstioCertificateResponse() {
        certChain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    private IstioCertificateResponse(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
            .newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            certChain_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        certChain_.add(s);
                        break;
                    }
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry,
                            tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                certChain_ = certChain_.getUnmodifiableView();
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return Ca.internal_static_istio_v1_auth_IstioCertificateResponse_descriptor;
    }

    public static IstioCertificateResponse parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IstioCertificateResponse parseFrom(java.nio.ByteBuffer data,
                                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IstioCertificateResponse parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IstioCertificateResponse parseFrom(com.google.protobuf.ByteString data,
                                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IstioCertificateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IstioCertificateResponse parseFrom(byte[] data,
                                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IstioCertificateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static IstioCertificateResponse parseFrom(java.io.InputStream input,
                                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static IstioCertificateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static IstioCertificateResponse parseDelimitedFrom(java.io.InputStream input,
                                                              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static IstioCertificateResponse parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static IstioCertificateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(IstioCertificateResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static IstioCertificateResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<IstioCertificateResponse> parser() {
        return PARSER;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(UnusedPrivateParameter unused) {
        return new IstioCertificateResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
        return Ca.internal_static_istio_v1_auth_IstioCertificateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(IstioCertificateResponse.class,
                Builder.class);
    }

    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     *
     * @return A list containing the certChain.
     */
    public com.google.protobuf.ProtocolStringList getCertChainList() {
        return certChain_;
    }

    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     *
     * @return The count of certChain.
     */
    public int getCertChainCount() {
        return certChain_.size();
    }

    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The certChain at the given index.
     */
    public String getCertChain(int index) {
        return certChain_.get(index);
    }

    /**
     * <pre>
     * PEM-encoded certificate chain.
     * The leaf cert is the first element, and the root cert is the last element.
     * </pre>
     *
     * <code>repeated string cert_chain = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the certChain at the given index.
     */
    public com.google.protobuf.ByteString getCertChainBytes(int index) {
        return certChain_.getByteString(index);
    }

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        for (int i = 0; i < certChain_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1,
                certChain_.getRaw(i));
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }
        size = 0;
        {
            int dataSize = 0;
            for (int i = 0; i < certChain_.size(); i++) {
                dataSize += computeStringSizeNoTag(certChain_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getCertChainList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof IstioCertificateResponse)) {
            return super.equals(obj);
        }
        IstioCertificateResponse other = (IstioCertificateResponse) obj;

        if (!getCertChainList().equals(other.getCertChainList())) {
            return false;
        }
        if (!unknownFields.equals(other.unknownFields)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getCertChainCount() > 0) {
            hash = (37 * hash) + CERT_CHAIN_FIELD_NUMBER;
            hash = (53 * hash) + getCertChainList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<IstioCertificateResponse> getParserForType() {
        return PARSER;
    }

    @Override
    public IstioCertificateResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * Certificate response message.
     * </pre>
     * <p>
     * Protobuf type {@code istio.v1.auth.IstioCertificateResponse}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:istio.v1.auth.IstioCertificateResponse)
        IstioCertificateResponseOrBuilder {

        private int bitField0_;
        private com.google.protobuf.LazyStringList certChain_ = com.google.protobuf.LazyStringArrayList.EMPTY;

        // Construct using istio.v1.auth.IstioCertificateResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return Ca.internal_static_istio_v1_auth_IstioCertificateResponse_descriptor;
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return Ca.internal_static_istio_v1_auth_IstioCertificateResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(IstioCertificateResponse.class,
                    Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            certChain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return Ca.internal_static_istio_v1_auth_IstioCertificateResponse_descriptor;
        }

        @Override
        public IstioCertificateResponse getDefaultInstanceForType() {
            return IstioCertificateResponse.getDefaultInstance();
        }

        @Override
        public IstioCertificateResponse build() {
            IstioCertificateResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IstioCertificateResponse buildPartial() {
            IstioCertificateResponse result = new IstioCertificateResponse(this);
            int from_bitField0_ = bitField0_;
            if (((bitField0_ & 0x00000001) != 0)) {
                certChain_ = certChain_.getUnmodifiableView();
                bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.certChain_ = certChain_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field, int index,
            Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof IstioCertificateResponse) {
                return mergeFrom((IstioCertificateResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(IstioCertificateResponse other) {
            if (other == IstioCertificateResponse.getDefaultInstance()) {
                return this;
            }
            if (!other.certChain_.isEmpty()) {
                if (certChain_.isEmpty()) {
                    certChain_ = other.certChain_;
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    ensureCertChainIsMutable();
                    certChain_.addAll(other.certChain_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            IstioCertificateResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (IstioCertificateResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureCertChainIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                certChain_ = new com.google.protobuf.LazyStringArrayList(certChain_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @return A list containing the certChain.
         */
        public com.google.protobuf.ProtocolStringList getCertChainList() {
            return certChain_.getUnmodifiableView();
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @return The count of certChain.
         */
        public int getCertChainCount() {
            return certChain_.size();
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The certChain at the given index.
         */
        public String getCertChain(int index) {
            return certChain_.get(index);
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the certChain at the given index.
         */
        public com.google.protobuf.ByteString getCertChainBytes(int index) {
            return certChain_.getByteString(index);
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The certChain to set.
         * @return This builder for chaining.
         */
        public Builder setCertChain(int index, String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureCertChainIsMutable();
            certChain_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @param value The certChain to add.
         * @return This builder for chaining.
         */
        public Builder addCertChain(String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureCertChainIsMutable();
            certChain_.add(value);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @param values The certChain to add.
         * @return This builder for chaining.
         */
        public Builder addAllCertChain(Iterable<String> values) {
            ensureCertChainIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, certChain_);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCertChain() {
            certChain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * PEM-encoded certificate chain.
         * The leaf cert is the first element, and the root cert is the last element.
         * </pre>
         *
         * <code>repeated string cert_chain = 1;</code>
         *
         * @param value The bytes of the certChain to add.
         * @return This builder for chaining.
         */
        public Builder addCertChainBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureCertChainIsMutable();
            certChain_.add(value);
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:istio.v1.auth.IstioCertificateResponse)

    }

}
